export const dummyAspirasi = [
    {
        id: 1,
        nama: "Anonim",
        tujuan: "Ketua BEM",
        isi: "Tolong tingkatkan transparansi anggaran kegiatan BEM, banyak mahasiswa yang ingin tahu kemana alokasi dana digunakan setiap semester.",
        created_at: "2026-03-10T08:30:00",
        expired_at: "2026-04-09T08:30:00",
        isAnon: true,
    },
    {
        id: 2,
        nama: "Budi Santoso",
        tujuan: "Departemen Akademik",
        isi: "Mohon adakan workshop dan seminar lebih sering khususnya terkait persiapan magang dan karier. Banyak dari kami yang masih bingung soal CV dan interview.",
        created_at: "2026-03-15T14:00:00",
        expired_at: "2026-04-14T14:00:00",
        isAnon: false,
    },
    {
        id: 3,
        nama: "Anonim",
        tujuan: "Departemen Minat Bakat",
        isi: "Fasilitas olahraga kampus perlu diperbaiki, lapangan basket sudah rusak dan tidak layak pakai. Mohon diperhatikan untuk kegiatan UKM. Fasilitas olahraga kampus perlu diperbaiki, lapangan basket sudah rusak dan tidak layak pakai. Mohon diperhatikan untuk kegiatan UKM. Fasilitas olahraga kampus perlu diperbaiki, lapangan basket sudah rusak dan tidak layak pakai. Mohon diperhatikan untuk kegiatan UKM. Fasilitas olahraga kampus perlu diperbaiki, lapangan basket sudah rusak dan tidak layak pakai. Mohon diperhatikan untuk kegiatan UKM.",
        created_at: "2026-03-20T10:15:00",
        expired_at: "2026-04-19T10:15:00",
        isAnon: true,
    },
    {
        id: 4,
        nama: "Citra Dewi",
        tujuan: "Ketua BEM",
        isi: "Saya mengusulkan agar ada program mentoring antara mahasiswa senior dan junior agar dapat mempercepat adaptasi mahasiswa baru.",
        created_at: "2026-03-25T09:00:00",
        expired_at: "2026-04-24T09:00:00",
        isAnon: false,
    },
    {
        id: 5,
        nama: "Anonim",
        tujuan: "Departemen Seni Budaya",
        isi: "Acara budaya tahun ini kurang berkesan dibanding tahun lalu. Harap lebih melibatkan mahasiswa dalam proses perencanaan agar lebih representatif.",
        created_at: "2026-04-01T16:45:00",
        expired_at: "2026-05-01T16:45:00",
        isAnon: true,
    },
];
